In [1]:
import pandas as pd
import numpy as np

In [2]:
path='/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/'

# BEGIN // dotyczy:
I am interested in exploring whether there is a difference in the ratio A/B between the two conditions. Just to clarify: I am not interested in finding out whether there are significant differences between A and B (there are), but whether those differences between A and B change between condition treated vs. untreated.

In [150]:
UTR = pd.read_csv(path+'mRNA_only_merged_w_XP.csv')
UTR.head(1)

,query,al_title,al_accession,evalue,coverage,Entry,Protein names,Gene names
0,TRINITY_DN100004_c4_g2_i2,gi|929290304|ref|XM_014166828.1| PREDICTED: Sa...,XM_014166828,0.0,100.183824,A0A1S3P3U9,forkhead box protein P4-like isoform X8,LOC106583051

In [151]:
UTR = UTR[['query', 'Entry']]
UTR.head(1)

                       query       Entry
0  TRINITY_DN100004_c4_g2_i2  A0A1S3P3U9

In [152]:
UTR.rename(columns={'query':'trinity'}, inplace=True)

In [153]:
UTR.head(1)

                     trinity       Entry
0  TRINITY_DN100004_c4_g2_i2  A0A1S3P3U9

In [154]:
matryca_novel = pd.read_csv(path+'PBS1d_MC_all_matryca.csv')
matryca_novel.head()

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,MC_6d_1,MC_6d_2,MC_6d_3,MC_9d_1,MC_9d_2,MC_9d_3
0,TRINITY_DN100003_c1_g1_i1,8,16,29,1,24,21,24,1,1,2,7,2,34
1,TRINITY_DN100004_c4_g2_i2,9,22,24,8,23,50,45,65,53,95,76,29,74
2,TRINITY_DN100005_c7_g2_i1,800,798,577,913,1322,1276,1285,6952,5736,4279,6616,4073,3119
3,TRINITY_DN100005_c8_g3_i1,101,102,92,248,52,56,71,89,189,138,313,327,278
4,TRINITY_DN100005_c9_g1_i1,19,4,22,4,2,2,1,0,1,0,2,6,18

In [21]:
matryca_novel.shape

(188998, 14)

In [164]:
matryca_w_entry = pd.merge(UTR, matryca_novel, on='trinity', how='inner')
matryca_w_entry.head()

,trinity,Entry,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,MC_6d_1,MC_6d_2,MC_6d_3,MC_9d_1,MC_9d_2,MC_9d_3
0,TRINITY_DN100004_c4_g2_i2,A0A1S3P3U9,9,22,24,8,23,50,45,65,53,95,76,29,74
1,TRINITY_DN100005_c7_g2_i1,A0A1S3SUX9,800,798,577,913,1322,1276,1285,6952,5736,4279,6616,4073,3119
2,TRINITY_DN81030_c8_g4_i1,A0A1S3SUX9,47,44,18,47,62,74,62,335,306,196,292,162,121
3,TRINITY_DN83202_c8_g4_i2,A0A1S3SUX9,35,21,30,30,13,28,32,8,6,13,21,15,38
4,TRINITY_DN105298_c5_g1_i2,A0A1S3SUX9,23,15,19,25,7,12,10,1,13,8,22,8,13

In [156]:
matryca_w_entry.shape #mamy tu tylko trinity zidentyfikowane jako mRNA bialka (UTR)

(93208, 15)

In [165]:
matryca_w_entry.columns = [str(col) + '_UTR' for col in matryca_w_entry.columns]

In [166]:
matryca_w_entry.rename(columns={'Entry_UTR':'Entry', 'trinity_UTR':'id_UTR'}, inplace=True)

In [167]:
matryca_w_entry.head()

,id_UTR,Entry,PBS_1d_1_UTR,PBS_1d_2_UTR,PBS_1d_3_UTR,PBS_1d_4_UTR,MC_1d_1_UTR,MC_1d_2_UTR,MC_1d_3_UTR,MC_6d_1_UTR,MC_6d_2_UTR,MC_6d_3_UTR,MC_9d_1_UTR,MC_9d_2_UTR,MC_9d_3_UTR
0,TRINITY_DN100004_c4_g2_i2,A0A1S3P3U9,9,22,24,8,23,50,45,65,53,95,76,29,74
1,TRINITY_DN100005_c7_g2_i1,A0A1S3SUX9,800,798,577,913,1322,1276,1285,6952,5736,4279,6616,4073,3119
2,TRINITY_DN81030_c8_g4_i1,A0A1S3SUX9,47,44,18,47,62,74,62,335,306,196,292,162,121
3,TRINITY_DN83202_c8_g4_i2,A0A1S3SUX9,35,21,30,30,13,28,32,8,6,13,21,15,38
4,TRINITY_DN105298_c5_g1_i2,A0A1S3SUX9,23,15,19,25,7,12,10,1,13,8,22,8,13

## BIAŁKA PROT

In [18]:
matryca_w_entry.head()

,Entry,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,MC_6d_1,MC_6d_2,MC_6d_3,MC_9d_1,MC_9d_2,MC_9d_3
0,A0A1S3P3U9,9,22,24,8,23,50,45,65,53,95,76,29,74
1,A0A1S3SUX9,800,798,577,913,1322,1276,1285,6952,5736,4279,6616,4073,3119
2,A0A1S3SUX9,47,44,18,47,62,74,62,335,306,196,292,162,121
3,A0A1S3SUX9,35,21,30,30,13,28,32,8,6,13,21,15,38
4,A0A1S3SUX9,23,15,19,25,7,12,10,1,13,8,22,8,13

In [12]:
# BIALKA:

salmo_rep_with_annot = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/1_code/report_salmo_annot_feature_map_salmo_proteins_xp01.csv', sep='\t', low_memory=False)

In [48]:
salmo_rep_with_annot.head()

                          id           ident
0     TRINITY_DN100000_c5_g1  XP_013978521.1
1  TRINITY_DN100000_c5_g1_i2  XP_014024532.1
2  TRINITY_DN100000_c5_g1_i6  XP_013978521.1
3     TRINITY_DN100000_c9_g1             NaN
4  TRINITY_DN100000_c9_g1_i1             NaN

In [13]:
salmo_rep_with_annot.shape

(332030, 2)

In [14]:
salmo_rep_with_annot.dropna(inplace=True)
salmo_rep_with_annot.shape

(257125, 2)

In [57]:
salmo_rep_with_annot.head()

                          id           ident
0     TRINITY_DN100000_c5_g1  XP_013978521.1
1  TRINITY_DN100000_c5_g1_i2  XP_014024532.1
2  TRINITY_DN100000_c5_g1_i6  XP_013978521.1
7     TRINITY_DN100001_c2_g2  XP_014027367.1
8  TRINITY_DN100001_c2_g2_i2  XP_014027367.1

In [41]:
salmo_rep_with_annot.dtypes

id       object
ident    object
dtype: object

In [52]:
salmo_rep_with_annot['ident'].to_csv(path+'xp_to_uniref.txt', index=False)

In [18]:
# zawiera wszystkie bialka zidentyfikowane przez trinotate i przypisane im Entry z uniprota

uniref_from_trinotate = pd.read_csv(prot_path+'uniprot-yourlist-xp_to_uniref.tab', sep='\t')
uniref_from_trinotate.head()

,Entry,ident,Entry name,Status,Protein names,Gene names,Organism,Length
0,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758
1,A0A1S3PAG0,XP_014024532.1,A0A1S3PAG0_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106584141,Salmo salar (Atlantic salmon),754
2,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333
3,B5X212,XP_014027367.1,CIO1B_SALSA,reviewed,Probable cytosolic iron-sulfur protein assembl...,ciao1b,Salmo salar (Atlantic salmon),333
4,A0A1S3NJU9,XP_014015694.1,A0A1S3NJU9_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106579887 CIAO1,Salmo salar (Atlantic salmon),330

In [112]:
#salmo_rep_with_annot_split = pd.DataFrame(salmo_rep_with_annot['ident'].str.split('^').tolist(), index=salmo_rep_with_annot.id).stack()
#salmo_rep_with_annot_split = salmo_rep_with_annot_split.reset_index([0, 'id'])
#salmo_rep_with_annot_split

In [113]:
#uniref_from_trinotate_entry_indent = uniref_from_trinotate[['Entry', 'ident']]
#uniref_from_trinotate_entry_indent.head()

In [19]:
salmo_rep_with_annot_w_entry = pd.merge(uniref_from_trinotate, salmo_rep_with_annot, on='ident', how='inner')
salmo_rep_with_annot_w_entry.head()

,Entry,ident,Entry name,Status,Protein names,Gene names,Organism,Length,id
0,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758,TRINITY_DN100000_c5_g1
1,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758,TRINITY_DN100000_c5_g1_i6
2,A0A1S3PAG0,XP_014024532.1,A0A1S3PAG0_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106584141,Salmo salar (Atlantic salmon),754,TRINITY_DN100000_c5_g1_i2
3,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333,TRINITY_DN100001_c2_g2
4,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333,TRINITY_DN100001_c2_g2_i2

In [20]:
salmo_rep_with_annot_w_entry.shape

(429071, 9)

In [22]:
salmo_rep_with_annot_w_entry.to_csv(prot_path+'PROT_wszystkie_bialka_z_raportu_trinity.csv', index=False)

In [116]:
prot_path = '/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/proteins_salmo/'
proteins_matryca = pd.read_csv(prot_path+'PBS_MCLR_salmo_only_matryca.csv')
proteins_matryca.head()

,id,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,MC_6d_1,MC_6d_2,MC_6d_3,MC_9d_1,MC_9d_2,MC_9d_3
0,TRINITY_DN100000_c5_g1_i2,0.0,3.0,2.0,0.0,0.0,0.0,0.0,0,0,0,5,0,0
1,TRINITY_DN100000_c5_g1_i6,374.0,506.0,607.0,594.0,511.0,726.0,517.0,192,195,227,427,219,339
2,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1162.0,1784.0,938.0,1730,1743,1974,2315,2067,2386
3,TRINITY_DN100001_c2_g2_i7,562.0,408.0,311.0,353.0,402.0,471.0,420.0,1378,1338,1428,1291,1139,1344
4,TRINITY_DN100001_c2_g3_i3,565.0,525.0,384.0,406.0,555.0,552.0,529.0,1553,1461,1684,1436,1416,1447

In [117]:
proteins_matryca.shape

(148647, 14)

In [118]:
proteins_matryca_w_entry = pd.merge(proteins_matryca, salmo_rep_with_annot_w_entry, on='id', how='inner')
proteins_matryca_w_entry.drop_duplicates(inplace=True)
proteins_matryca_w_entry.shape

(149296, 22)

In [96]:
#proteins_matryca_w_entry.to_csv(path+'test.csv')

In [119]:
test_if_merged_correctly = proteins_matryca_w_entry[~proteins_matryca_w_entry['id'].isin(proteins_matryca['id'])]
test_if_merged_correctly.shape

(0, 22)

In [98]:
#del proteins_matryca_w_entry['id']
#del proteins_matryca_w_entry['ident']

In [120]:
proteins_matryca_w_entry.columns = [str(col) + '_PROT' for col in proteins_matryca_w_entry.columns]

In [122]:
proteins_matryca_w_entry.rename(columns={'Entry_PROT':'Entry'}, inplace=True)

In [123]:
proteins_matryca_w_entry.head()

,id_PROT,PBS_1d_1_PROT,PBS_1d_2_PROT,PBS_1d_3_PROT,PBS_1d_4_PROT,MC_1d_1_PROT,MC_1d_2_PROT,MC_1d_3_PROT,MC_6d_1_PROT,MC_6d_2_PROT,...,MC_9d_2_PROT,MC_9d_3_PROT,Entry,ident_PROT,Entry name_PROT,Status_PROT,Protein names_PROT,Gene names_PROT,Organism_PROT,Length_PROT
0,TRINITY_DN100000_c5_g1_i2,0.0,3.0,2.0,0.0,0.0,0.0,0.0,0,0,...,0,0,A0A1S3PAG0,XP_014024532.1,A0A1S3PAG0_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106584141,Salmo salar (Atlantic salmon),754
1,TRINITY_DN100000_c5_g1_i6,374.0,506.0,607.0,594.0,511.0,726.0,517.0,192,195,...,219,339,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758
2,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1162.0,1784.0,938.0,1730,1743,...,2067,2386,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333
3,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1162.0,1784.0,938.0,1730,1743,...,2067,2386,B5X212,XP_014027367.1,CIO1B_SALSA,reviewed,Probable cytosolic iron-sulfur protein assembl...,ciao1b,Salmo salar (Atlantic salmon),333
4,TRINITY_DN100001_c2_g2_i7,562.0,408.0,311.0,353.0,402.0,471.0,420.0,1378,1338,...,1139,1344,A0A1S3NJU9,XP_014015694.1,A0A1S3NJU9_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106579887 CIAO1,Salmo salar (Atlantic salmon),330

In [124]:
matryca_w_entry.shape #UTR

(93208, 14)

In [125]:
proteins_matryca_w_entry.shape #PROT

(149296, 22)

In [168]:
# do UTR dodac PROT

merged_UTR_PROT_matryca = pd.merge(matryca_w_entry, proteins_matryca_w_entry, on="Entry", how='inner')
#merged.to_csv(path+'matryca_UTR_PROT_entry_only.csv', index=False)

In [169]:
merged_UTR_PROT_matryca.columns

Index(['id_UTR', 'Entry', 'PBS_1d_1_UTR', 'PBS_1d_2_UTR', 'PBS_1d_3_UTR',
       'PBS_1d_4_UTR', 'MC_1d_1_UTR', 'MC_1d_2_UTR', 'MC_1d_3_UTR',
       'MC_6d_1_UTR', 'MC_6d_2_UTR', 'MC_6d_3_UTR', 'MC_9d_1_UTR',
       'MC_9d_2_UTR', 'MC_9d_3_UTR', 'id_PROT', 'PBS_1d_1_PROT',
       'PBS_1d_2_PROT', 'PBS_1d_3_PROT', 'PBS_1d_4_PROT', 'MC_1d_1_PROT',
       'MC_1d_2_PROT', 'MC_1d_3_PROT', 'MC_6d_1_PROT', 'MC_6d_2_PROT',
       'MC_6d_3_PROT', 'MC_9d_1_PROT', 'MC_9d_2_PROT', 'MC_9d_3_PROT',
       'ident_PROT', 'Entry name_PROT', 'Status_PROT', 'Protein names_PROT',
       'Gene names_PROT', 'Organism_PROT', 'Length_PROT'],
      dtype='object')

In [130]:
day_1_matryca = merged_UTR_PROT_matryca[['PBS_1d_1_UTR', 'PBS_1d_2_UTR', 'PBS_1d_3_UTR', 'PBS_1d_4_UTR',
       'MC_1d_1_UTR', 'MC_1d_2_UTR', 'MC_1d_3_UTR', 'PBS_1d_1_PROT', 'PBS_1d_2_PROT',
       'PBS_1d_3_PROT', 'PBS_1d_4_PROT', 'MC_1d_1_PROT', 'MC_1d_2_PROT',
       'MC_1d_3_PROT']]

day_1_matryca.to_csv(path+'day_1_UTR_PROT_matryca.csv', index=False)

# na podstawie powyzszego ^^ robiebie deseq2

In [178]:
# ponizej wczytuje wyniki deseq i dodaje do nich kolumny z merged_UTR_PROT_matryca

deseq_day_1_results = pd.read_csv(path+'deseq2_result_from_R_1d.csv')

In [179]:
merged_UTR_PROT_matryca.shape

(295223, 36)

In [183]:
deseq_day_1_results.shape

(295223, 6)

In [184]:
deseq_day_1_results_w_all_details = pd.merge(deseq_day_1_results, merged_UTR_PROT_matryca, left_index=True, right_index=True)
deseq_day_1_results_w_all_details.shape

(295223, 42)

In [185]:
deseq_day_1_results_w_all_details = deseq_day_1_results_w_all_details[['baseMean', 'log2FoldChange', 'lfcSE', 'stat', 'pvalue', 'padj',
       'Entry', 'PBS_1d_1_UTR', 'PBS_1d_2_UTR', 'PBS_1d_3_UTR', 'PBS_1d_4_UTR',
       'MC_1d_1_UTR', 'MC_1d_2_UTR', 'MC_1d_3_UTR', 'id_UTR', 'id_PROT', 'PBS_1d_1_PROT', 'PBS_1d_2_PROT',
       'PBS_1d_3_PROT', 'PBS_1d_4_PROT', 'MC_1d_1_PROT', 'MC_1d_2_PROT',
       'MC_1d_3_PROT', 'ident_PROT', 'Entry name_PROT', 'Status_PROT', 'Protein names_PROT',
       'Gene names_PROT', 'Organism_PROT', 'Length_PROT']]

In [186]:
deseq_day_1_results_w_all_details = deseq_day_1_results_w_all_details[deseq_day_1_results_w_all_details['padj'] < 0.001]

In [187]:
deseq_day_1_results_w_all_details.sort_values(by='log2FoldChange', inplace=True)

In [188]:
deseq_day_1_results_w_all_details.to_csv(path+'deseq_result_1d_with_all_details.csv', index=False)

# END ///// dotyczy:
I am interested in exploring whether there is a difference in the ratio A/B between the two conditions. Just to clarify: I am not interested in finding out whether there are significant differences between A and B (there are), but whether those differences between A and B change between condition treated vs. untreated.

# BEGIN /// 
### deseq UTR i PROT oddzielnie i porownanie ze soba juz tylko wynikow log2fc

najpierw: deseq wszystkich sekwencji (matryca novel), a potem wybranie z nich mRNA

## UTR

In [85]:
matryca_novel = pd.read_csv(path+'PBS1d_MC_all_matryca.csv')
matryca_novel.head()

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,MC_6d_1,MC_6d_2,MC_6d_3,MC_9d_1,MC_9d_2,MC_9d_3
0,TRINITY_DN100003_c1_g1_i1,8,16,29,1,24,21,24,1,1,2,7,2,34
1,TRINITY_DN100004_c4_g2_i2,9,22,24,8,23,50,45,65,53,95,76,29,74
2,TRINITY_DN100005_c7_g2_i1,800,798,577,913,1322,1276,1285,6952,5736,4279,6616,4073,3119
3,TRINITY_DN100005_c8_g3_i1,101,102,92,248,52,56,71,89,189,138,313,327,278
4,TRINITY_DN100005_c9_g1_i1,19,4,22,4,2,2,1,0,1,0,2,6,18

In [4]:
matryca_novel.shape

(188998, 14)

In [8]:
#matryca_novel.to_csv(path+'matryca.csv', index=False)

In [44]:
matryca_novel.columns

Index(['trinity', 'PBS_1d_1', 'PBS_1d_2', 'PBS_1d_3', 'PBS_1d_4', 'MC_1d_1',
       'MC_1d_2', 'MC_1d_3', 'MC_6d_1', 'MC_6d_2', 'MC_6d_3', 'MC_9d_1',
       'MC_9d_2', 'MC_9d_3'],
      dtype='object')

In [38]:
matryca_novel_1d = matryca_novel[['trinity', 'PBS_1d_1', 'PBS_1d_2', 'PBS_1d_3', 'PBS_1d_4', 'MC_1d_1',
       'MC_1d_2', 'MC_1d_3']]

In [6]:
matryca_novel_6d = matryca_novel[['trinity', 'PBS_1d_1', 'PBS_1d_2', 'PBS_1d_3', 'PBS_1d_4', 'MC_6d_1',
       'MC_6d_2', 'MC_6d_3']]

In [7]:
matryca_novel_9d = matryca_novel[['trinity', 'PBS_1d_1', 'PBS_1d_2', 'PBS_1d_3', 'PBS_1d_4', 'MC_9d_1',
       'MC_9d_2', 'MC_9d_3']]

In [39]:
# po deseq2:

#zaladuj wyniki deseq
novel_deseq_results_d1 = pd.read_csv(path+'NOVEL_deseq2_result_from_R_1d.csv')

In [9]:
# po deseq2:

#zaladuj wyniki deseq
novel_deseq_results_d6 = pd.read_csv(path+'NOVEL_deseq2_result_from_R_6d.csv')

In [10]:
# po deseq2:

#zaladuj wyniki deseq
novel_deseq_results_d9 = pd.read_csv(path+'NOVEL_deseq2_result_from_R_9d.csv')

In [33]:
# dodaj kolumny trinity oraz RC poszczegolnych grup do wynikow deseq:
novel_deseq_results_d9 = pd.concat([matryca_novel_9d, novel_deseq_results_d9], axis=1, sort=False)

In [34]:
novel_deseq_results_d6.head()

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_6d_1,MC_6d_2,MC_6d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
77360,TRINITY_DN80414_c8_g1_i6,0,0,0,0,1194,1712,2219,661.890546,-12.989923,1.107723,-11.726692,9.302378e-32,1.469152e-29
94281,TRINITY_DN92637_c2_g3_i1,0,0,0,4,3452,9986,9184,2947.462247,-12.718373,0.911600,-13.951706,3.071686e-44,1.311542e-41
79244,TRINITY_DN95065_c7_g1_i9,0,0,0,2,1061,1825,1700,593.720454,-11.393443,1.096414,-10.391553,2.709051e-25,2.355093e-23
115957,TRINITY_DN106993_c0_g2_i1,0,1,0,0,524,667,1601,360.860625,-11.392848,1.153008,-9.880982,5.033712e-23,3.542948e-21
93203,TRINITY_DN83711_c3_g5_i1,0,0,0,0,630,691,384,218.579709,-11.391514,1.110907,-10.254250,1.132517e-24,9.356048e-23

In [24]:
novel_deseq_results_d1 = novel_deseq_results_d1[novel_deseq_results_d1['padj'] < 0.001]

In [43]:
novel_deseq_results_d1.sort_values(by='log2FoldChange', inplace=True)

In [25]:
novel_deseq_results_d6 = novel_deseq_results_d6[novel_deseq_results_d6['padj'] < 0.001]

In [26]:
novel_deseq_results_d6.sort_values(by='log2FoldChange', inplace=True)

In [35]:
novel_deseq_results_d9 = novel_deseq_results_d9[novel_deseq_results_d9['padj'] < 0.001]

In [36]:
novel_deseq_results_d9.sort_values(by='log2FoldChange', inplace=True)

In [53]:
novel_deseq_results_d1.to_csv(path+'NOVEL_deseq2_result_from_R_1d_padj-filtered_l2fc-sorted.csv', index=False)

In [ ]:
# filtrowanie tylko mRNA UTR ze wszystkich trinity, ktore to zawiera powyzsza matryca

In [37]:
UTR = pd.read_csv(path+'mRNA_only_merged_w_XP.csv')
UTR.head(1)

,query,al_title,al_accession,evalue,coverage,Entry,Protein names,Gene names
0,TRINITY_DN100004_c4_g2_i2,gi|929290304|ref|XM_014166828.1| PREDICTED: Sa...,XM_014166828,0.0,100.183824,A0A1S3P3U9,forkhead box protein P4-like isoform X8,LOC106583051

In [38]:
UTR = UTR[['query', 'Entry', 'Protein names']]
UTR.head(1)

,query,Entry,Protein names
0,TRINITY_DN100004_c4_g2_i2,A0A1S3P3U9,forkhead box protein P4-like isoform X8

In [39]:
UTR.rename(columns={'query':'trinity'}, inplace=True)

In [40]:
UTR.head(1)

,trinity,Entry,Protein names
0,TRINITY_DN100004_c4_g2_i2,A0A1S3P3U9,forkhead box protein P4-like isoform X8

In [41]:
mRNA_deseq_results_d9 = pd.merge(UTR, novel_deseq_results_d9, on='trinity', how='inner')
mRNA_deseq_results_d9.head()

,trinity,Entry,Protein names,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_9d_1,MC_9d_2,MC_9d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,TRINITY_DN100005_c7_g2_i1,A0A1S3SUX9,"alpha-N-acetylgalactosaminide alpha-2,6-sialyl...",800,798,577,913,6616,4073,3119,2050.110876,-2.022177,0.408863,-4.945852,7.581172e-07,1.101775e-05
1,TRINITY_DN110347_c4_g1_i2,A0A1S3RIW2,voltage-gated potassium channel subunit beta-2...,1246,1439,1081,1869,32,11,255,953.007779,4.455068,0.804014,5.541031,3.006951e-08,6.254534e-07
2,TRINITY_DN81835_c7_g1_i1,A0A1S3RIW2,voltage-gated potassium channel subunit beta-2...,1686,2005,1513,2852,53,32,339,1360.091690,4.452888,0.708102,6.288481,3.205872e-10,1.069100e-08
3,TRINITY_DN86495_c7_g1_i7,C0HBG6,Ras-related and estrogen-regulated growth inhi...,11,15,7,21,69,263,241,71.252965,-3.245441,0.617382,-5.256778,1.466009e-07,2.568730e-06
4,TRINITY_DN100021_c4_g1_i2,A0A1B1PFD7,NFAT5a2 (nuclear factor of activated T-cells 5...,40,53,36,18,178,197,209,88.715668,-1.816671,0.473409,-3.837425,1.243310e-04,9.341171e-04

In [49]:
#mamy tu wynik deseq 1d dla UTR (zidentyfikowane jako mRNA w blast'cie)
#deseq robiony w R
#teraz wystarczy zrobic jeszcze deseq dla 1d bialek prawdziwych (;)) i porownac je po entry z tymi tu UTR'ami
mRNA_deseq_results_d1.shape

(3010, 16)

In [30]:
mRNA_deseq_results_d6.shape

(14158, 16)

In [42]:
mRNA_deseq_results_d9.shape

(10038, 16)

In [43]:
mRNA_deseq_results_d9.drop_duplicates(inplace=True)
mRNA_deseq_results_d9.shape

(10038, 16)

## PROT

In [44]:
prot_path='/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/proteins_salmo/'

In [45]:
matryca_salmo_prot = pd.read_csv(prot_path+'PBS_MCLR_salmo_only_matryca.csv')
matryca_salmo_prot.head()

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,MC_6d_1,MC_6d_2,MC_6d_3,MC_9d_1,MC_9d_2,MC_9d_3
0,TRINITY_DN100000_c5_g1_i2,0.0,3.0,2.0,0.0,0.0,0.0,0.0,0,0,0,5,0,0
1,TRINITY_DN100000_c5_g1_i6,374.0,506.0,607.0,594.0,511.0,726.0,517.0,192,195,227,427,219,339
2,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1162.0,1784.0,938.0,1730,1743,1974,2315,2067,2386
3,TRINITY_DN100001_c2_g2_i7,562.0,408.0,311.0,353.0,402.0,471.0,420.0,1378,1338,1428,1291,1139,1344
4,TRINITY_DN100001_c2_g3_i3,565.0,525.0,384.0,406.0,555.0,552.0,529.0,1553,1461,1684,1436,1416,1447

In [8]:
matryca_salmo_prot_1d = matryca_salmo_prot[['trinity', 'PBS_1d_1', 'PBS_1d_2', 'PBS_1d_3', 'PBS_1d_4', 'MC_1d_1',
       'MC_1d_2', 'MC_1d_3']]

In [46]:
matryca_salmo_prot_6d = matryca_salmo_prot[['trinity', 'PBS_1d_1', 'PBS_1d_2', 'PBS_1d_3', 'PBS_1d_4', 'MC_6d_1',
       'MC_6d_2', 'MC_6d_3']]

In [47]:
matryca_salmo_prot_9d = matryca_salmo_prot[['trinity', 'PBS_1d_1', 'PBS_1d_2', 'PBS_1d_3', 'PBS_1d_4', 'MC_9d_1',
       'MC_9d_2', 'MC_9d_3']]

In [ ]:
# deseq wszystkich bialek

In [6]:
# po deseq2:

#zaladuj wyniki deseq
prot_deseq_results_d1 = pd.read_csv(prot_path+'PROT_deseq2_result_from_R_1d.csv')

In [48]:
# po deseq2:

#zaladuj wyniki deseq
prot_deseq_results_d6 = pd.read_csv(prot_path+'PROT_deseq2_result_from_R_6d.csv')

In [49]:
# po deseq2:

#zaladuj wyniki deseq
prot_deseq_results_d9 = pd.read_csv(prot_path+'PROT_deseq2_result_from_R_9d.csv')

In [9]:
# dodaj kolumny trinity oraz RC poszczegolnych grup do wynikow deseq:
prot_deseq_results_d1 = pd.concat([matryca_salmo_prot_1d, prot_deseq_results_d1], axis=1, sort=False)

In [50]:
# dodaj kolumny trinity oraz RC poszczegolnych grup do wynikow deseq:
prot_deseq_results_d6 = pd.concat([matryca_salmo_prot_6d, prot_deseq_results_d6], axis=1, sort=False)

In [51]:
# dodaj kolumny trinity oraz RC poszczegolnych grup do wynikow deseq:
prot_deseq_results_d9 = pd.concat([matryca_salmo_prot_9d, prot_deseq_results_d9], axis=1, sort=False)

In [11]:
prot_deseq_results_d1.head()

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,TRINITY_DN100000_c5_g1_i2,0.0,3.0,2.0,0.0,0.0,0.0,0.0,0.749348,2.942381,3.733119,0.788183,0.430590,NaN
1,TRINITY_DN100000_c5_g1_i6,374.0,506.0,607.0,594.0,511.0,726.0,517.0,536.444545,0.003718,0.298455,0.012459,0.990060,0.996488
2,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1162.0,1784.0,938.0,1160.929051,-0.011349,0.227672,-0.049846,0.960245,0.984625
3,TRINITY_DN100001_c2_g2_i7,562.0,408.0,311.0,353.0,402.0,471.0,420.0,408.751557,0.054736,0.284350,0.192495,0.847354,0.935092
4,TRINITY_DN100001_c2_g3_i3,565.0,525.0,384.0,406.0,555.0,552.0,529.0,491.319090,-0.085350,0.253452,-0.336748,0.736307,0.880355

In [ ]:
# dodanie "Entry bialek (i reszty informacji o bialkach z raportu trinity)" do matrycy z wynikami deseq
# plik importowany ponizej pochodzi z sekcji na samej gorze.

In [52]:
prot_all_from_trinity_report = pd.read_csv(prot_path+'PROT_wszystkie_bialka_z_raportu_trinity.csv')
prot_all_from_trinity_report.head(1)

,Entry,ident,Entry name,Status,Protein names,Gene names,Organism,Length,id
0,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758,TRINITY_DN100000_c5_g1

In [53]:
prot_all_from_trinity_report.rename(columns={'id':'trinity'}, inplace=True)

In [27]:
prot_deseq_results_d1_merged_prot_details = pd.merge(prot_deseq_results_d1, prot_all_from_trinity_report, on='trinity', how='inner')
prot_deseq_results_d1_merged_prot_details

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,baseMean,log2FoldChange,...,pvalue,padj,Entry,ident,Entry name,Status,Protein names,Gene names,Organism,Length
0,TRINITY_DN100000_c5_g1_i2,0.0,3.0,2.0,0.0,0.0,0.0,0.0,0.749348,2.942381,...,4.305896e-01,NaN,A0A1S3PAG0,XP_014024532.1,A0A1S3PAG0_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106584141,Salmo salar (Atlantic salmon),754
1,TRINITY_DN100000_c5_g1_i6,374.0,506.0,607.0,594.0,511.0,726.0,517.0,536.444545,0.003718,...,9.900598e-01,9.964880e-01,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758
2,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1162.0,1784.0,938.0,1160.929051,-0.011349,...,9.602448e-01,9.846255e-01,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333
3,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1162.0,1784.0,938.0,1160.929051,-0.011349,...,9.602448e-01,9.846255e-01,B5X212,XP_014027367.1,CIO1B_SALSA,reviewed,Probable cytosolic iron-sulfur protein assembl...,ciao1b,Salmo salar (Atlantic salmon),333
4,TRINITY_DN100001_c2_g2_i7,562.0,408.0,311.0,353.0,402.0,471.0,420.0,408.751557,0.054736,...,8.473543e-01,9.350916e-01,A0A1S3NJU9,XP_014015694.1,A0A1S3NJU9_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106579887 CIAO1,Salmo salar (Atlantic salmon),330
5,TRINITY_DN100001_c2_g2_i7,562.0,408.0,311.0,353.0,402.0,471.0,420.0,408.751557,0.054736,...,8.473543e-01,9.350916e-01,B5X9P2,XP_014015694.1,CIO1A_SALSA,reviewed,Probable cytosolic iron-sulfur protein assembl...,ciao1a,Salmo salar (Atlantic salmon),330
6,TRINITY_DN100001_c2_g3_i3,565.0,525.0,384.0,406.0,555.0,552.0,529.0,491.319090,-0.085350,...,7.363066e-01,8.803554e-01,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333
7,TRINITY_DN100001_c2_g3_i3,565.0,525.0,384.0,406.0,555.0,552.0,529.0,491.319090,-0.085350,...,7.363066e-01,8.803554e-01,B5X212,XP_014027367.1,CIO1B_SALSA,reviewed,Probable cytosolic iron-sulfur protein assembl...,ciao1b,Salmo salar (Atlantic salmon),333
8,TRINITY_DN100001_c2_g5_i1,408.0,396.0,299.0,269.0,322.0,336.0,303.0,327.589884,0.235980,...,3.828576e-01,6.413399e-01,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333
9,TRINITY_DN100001_c2_g5_i1,408.0,396.0,299.0,269.0,322.0,336.0,303.0,327.589884,0.235980,...,3.828576e-01,6.413399e-01,B5X212,XP_014027367.1,CIO1B_SALSA,reviewed,Probable cytosolic iron-sulfur protein assembl...,ciao1b,Salmo salar (Atlantic salmon),333
10,TRINITY_DN100002_c2_g3_i5,1.0,2.0,1.0,10.0,0.0,4.0,14.0,4.616783,-0.805314,...,6.125792e-01,8.101140e-01,A0A1S3MVZ1,XP_014007388.1,A0A1S3MVZ1_SALSA,unreviewed,"histone-lysine N-methyltransferase, H3 lysine-...",LOC106575408,Salmo salar (Atlantic salmon),606
11,TRINITY_DN100003_c1_g2_i1,38.0,72.0,58.0,24.0,71.0,94.0,57.0,57.179756,-0.439950,...,3.702836e-01,6.302572e-01,A0A1S3MUW9,XP_014007013.1,A0A1S3MUW9_SALSA,unreviewed,glycogenin-1-like,LOC106575201,Salmo salar (Atlantic salmon),251
12,TRINITY_DN100003_c1_g2_i1,38.0,72.0,58.0,24.0,71.0,94.0,57.0,57.179756,-0.439950,...,3.702836e-01,6.302572e-01,A0A1S3MUW9,XP_014007013.1,A0A1S3MUW9_SALSA,unreviewed,glycogenin-1-like,LOC106575201,Salmo salar (Atlantic salmon),251
13,TRINITY_DN100003_c1_g2_i6,74.0,106.0,86.0,51.0,152.0,154.0,139.0,105.664117,-0.756193,...,4.231092e-02,1.702625e-01,A0A1S3MUW9,XP_014007013.1,A0A1S3MUW9_SALSA,unreviewed,glycogenin-1-like,LOC106575201,Salmo salar (Atlantic salmon),251
14,TRINITY_DN100003_c1_g2_i6,74.0,106.0,86.0,51.0,152.0,154.0,139.0,105.664117,-0.756193,...,4.231092e-02,1.702625e-01,A0A1S3MUW9,XP_014007013.1,A0A1S3MUW9_SALSA,unreviewed,glycogenin-1-like,LOC106575201,Salmo salar (Atlantic salmon),251
15,TRINITY_DN100003_c1_g3_i1,97.0,150.0,145.0,24.0,184.0,145.0,162.0,127.865808,-0.502880,...,4.021154e-01,6.573780e-01,A0A1S3MUW9,XP_014007013.1,A0A1S3MUW9_SALSA,unreviewed,glycogenin-1-like,LOC106575201,Salmo salar (Atlantic salmon),251
16,TRINITY_DN100003_c1_g3_i1,97.0,150.0,145.0,24.0,184.0,145.0,162.0,127.865808,-0.502880,...,4.021154e-01,6.573780e-01,A0A1S3MUW9,XP_014007013.1,A0A1S3MUW9_SALSA,unreviewed,glycogenin-1-like,LOC106575201,Salmo salar (Atlantic salmon),251
17,TRINITY_DN100004_c3_g1_i17,61.0,49.0,63.0,47.0,60.0,48.0,39.0,51.859248,0.326307,...,4.117960e-01,6.656045e-01,A0A1S3M6G3,XP_013998645.1,A0A1S3M6G3_SALSA,unreviewed,keratin-associated protein 10-11-like,LOC106570697,Salmo salar (Atlantic salmon),241
18,TRINITY_DN100004_c3_g1_i17,61.0,49.0,63.0,47.0,60.0,48.0,39.0,51.859248,0.326307,...,4.117960e-01,6.656045e-01,A0A1S3M6G3,XP_013998645.1,A0A1S3M6G3_SALSA,unreviewed,keratin-associated protein 10-11-like,LOC106570697,Salmo salar (Atlantic salmon),241
19,TRINITY_DN100004_c4_g1_i4,0.0,0.0,7.0,0.0,0.0,5.0,5.0,2.495589,-0.640871,...,8.075859e-01,NaN,A0A1S3LC57,XP_013988543.1,A0A1S3LC57_SALSA,unreviewed,forkhead box protein P4-like isoform X1,LOC106565700,Salmo salar (Atlantic salmon),723
20,TRINITY_DN100004_c4_g1_i4,0.0,0.0,7.0,0.0,0.0,5.0,5.0,2.495589,-0.640871,...,8.075859e-01,NaN,A0A1S3LC57,XP_013988543.1,A0A1S3LC57_SALSA,unreviewed,forkhead box protein P4-like isoform X1,LOC106565700,Salmo salar (Atlantic salmon),723
21,TRINITY_DN100004_c4_g1_i7,48.0,65.0,36.0,46.0,118.0,184.0,194.0,94.733752,-1.646117,...,1.945841e-05,3.405019e-04,A0A1S3P409,XP_014022296.1,A0A1S3P409_SALSA,unreviewed,forkhead box protein P4-like isoform X2,LOC106583051,Salmo salar (Atlantic salmon),707
22,TRINITY_DN100005_c10_g1_i1,1.0,1.0,5.0,3.0,0.0,1.0,5.0,2.418991,0.382661,...,8.226483e-01,NaN,A0A1S3RRL5,XP_014054961.1,A0A1S3RRL5_SALSA,unreviewed,CD97 antigen-like,LOC106604643,Salmo salar (Atlantic salmon),248
23,TRINITY_DN100005_c10_g1_i1,1.0,1.0,5.0,3.0,0.0,1.0,5.0,2.418991,0.382661,...,8.226483e-01,NaN,A0A1S3RRL5,XP_014054961.1,A0A1S3RRL5_SALSA,unreviewed,CD97 antigen-like,LOC106604643,Salmo salar (Atlantic salmon),248
24,TRINITY_DN100005_c1_g1_i1,13.0,9.0,11.0,12.0,3.0,3.0,3.0,7.793454,2.052827,...,1.664610e-02,8.849854e-02,A0A1S3NFF3,XP_014013975.1,A0A1S3NFF3_SALSA,unreviewed,dendritic cell-specific transmembrane protein-...,LOC106579055,Salmo salar (Atlantic salmon),396
25,TRINITY_DN100005_c1_g1_i1,13.0,9.0,11.0,12.0,3.0,3.0,3.0,7.793454,2.052827,...,1.664610e-02,8.849854e-02,A0A1S3NFF3,XP_014013975.1,A0A1S3NFF3_SALSA,unreviewed,dendritic cell-specific transmembrane protein-...,LOC106579055,Salmo salar (Atlantic salmon),396
26,TRINITY_DN100005_c8_g4_i1,42.0,26.0,47.0,33.0,13.0,30.0,4.0,27.653586,1.508340,...,2.296490e-02,1.114693e-01,A0A1S3MB99,XP_014000314.1,A0A1S3MB99_SALSA,unreviewed,Serine/threonine protein phosphatase 2A regula...,LOC106571593,Salmo salar (Atlantic salmon),524
27,TRINITY_DN100005_c8_g4_i1,42.0,26.0,47.0,33.0,13.0,30.0,4.0,27.653586,1.508340,...,2.296490e-02,1.114693e-01,A0A1S3MB99,XP_014000314.1,A0A1S3MB99_SALSA,unreviewed,Serine/threonine protein phosphatase 2A regula...,LOC106571593,Salmo salar (Atlantic salmon),524
28,TRINITY_DN100006_c3_g1_i2,551.0,851.0,740.0,396.0,26.0,87.0,21.0,390.921318,4.083749,...,1.668645e-16,2.272009e-14,A0A1S3KR13,XP_013981062.1,A0A1S3KR13_SALSA,unreviewed,neutrophil gelatinase-associated lipocalin iso...,lcn2,Salmo salar (Atlantic salmon),188
29,TRINITY_DN100006_c4_g2_i12,80060.0,72696.0,66734.0,38541.0,120442.0,110225.0,48466.0,73738.905101,-0.334100,...,3.797074e-01,6.385575e-01,A0A1S3KQT5,XP_013981071.1,A0A1S3KQT5_SALSA,unreviewed,neutrophil gelatinase-associated lipocalin iso...,lcn2,Salmo salar (Atlantic salmon),184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246765,TRINITY_DN99994_c5_g3_i1,28.0,38.0,24.0,10.0,7.0,14.0,0.0,17.126591,2.109694,...,2.649726e-02,1.235657e-01,A0A1S3PLF4,XP_014028482.1,A0A1S3PLF4_SALSA,unreviewed,cytochrome P450 2D6-like isoform X1,LOC106586122,Salmo salar (Atlantic salmon),440
246766,TRINITY_DN99994_c6_g1_i1,45.0,47.0,26.0,43.0,0.0,2.0,0.0,23.465973,6.087759,...,1.925356e-07,5.460412e-06,A0A1S3MLL5,XP_014003715.1,A0A1S3MLL5_SALSA,unreviewed,bile acid receptor-like isoform X3,LOC106573302,Salmo salar (Atlantic salmon),429
246767,TRINITY_DN99994_c6_g1_i1,45.0,47.0,26.0,43.0,0.0,2.0,0.0,23.465973,6.087759,...,1.925356e-07,5.460412e-06,A0A1S3MLL5,XP_014003715.1,A0A1S3MLL5_SALSA,unreviewed,bile acid receptor-like isoform X3,LOC106573302,Salmo salar (Atlantic salmon),429
246768,TRINITY_DN99995_c0_g1_i4,35.0,113.0,24.0,92.0,76.0,372.0,58.0,98.237808,-1.107568,...,1.172045e-01,3.263494e-01,A0A1S3MT88,XP_014006387.1,A0A1S3MT88_SALSA,unreviewed,transmembrane protein 116-like isoform X1,LOC106574818,Salmo salar (Atlantic salmon),378
246769,TRINITY_DN99995_c0_g1_i4,35.0,113.0,24.0,92.0,76.0,372.0,58.0,98.237808,-1.107568,...,1.172045e-01,3.263494e-01,A0A1S3MT88,XP_014006387.1,A0A1S3MT88_SALSA,unreviewed,transmembrane protein 116-like isoform X1,LOC106574818,Salmo salar (Atlantic salmon),378
246770,TRINITY_DN99996_c5_g1_i4,64.0,24.0,52.0,178.0,309.0,487.0,726.0,254.592525,-2.599558,...,4.954432e-05,7.643188e-04,A0A1S3N366,XP_014009909.1,A0A1S3N366_SALSA,unreviewed,platelet receptor Gi24 isoform X2,cssa18h10orf54,Salmo salar (Atlantic salmon),301
246771,TRINITY_DN99996_c6_g3_i4,20.0,36.0,38.0,9.0,6.0,15.0,0.0,17.865868,2.193707,...,2.856635e-02,1.301898e-01,A0A1S3L705,XP_013986747.1,A0A1S3L705_SALSA,unreviewed,ERO1-like protein beta isoform X3,LOC106564835,Salmo salar (Atlantic salmon),449
246772,TRINITY_DN99996_c6_g3_i4,20.0,36.0,38.0,9.0,6.0,15.0,0.0,17.865868,2.193707,...,2.856635e-02,1.301898e-01,A0A1S3L705,XP_013986747.1,A0A1S3L705_SALSA,unreviewed,ERO1-like protein beta isoform X3,LOC106564835,Salmo salar (Atlantic salmon),449
246773,TRINITY_DN99997_c10_g1_i1,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.495525,2.329228,...,5.358111e-01,NaN,A0A1S3SR62,XP_014066833.1,A0A1S3SR62_SALSA,unreviewed,ribose-5-phosphate isomerase-like,LOC106611309,Salmo salar (Atlantic salmon),235
246774,TRINITY_DN99997_c2_g2_i1,51.0,60.0,49.0,62.0,33.0,159.0,74.0,66.050543,-0.475209,...,3.560277e-01,6.170034e-01,A0A1S3RXN1,XP_014056652.1,A0A1S3RXN1_SALSA,unreviewed,Purine nucleoside phosphorylase (EC 2.4.2.1) (...,LOC106605471,Salmo salar (Atlantic salmon),298
246775,TRINITY_DN99997_c2_g2_i1,51.0,60.0,49.0,62.0,33.0,159.0,74.0,66.050543,-0.475209,...,3.560277e-01,6.170034e-01,A0A1S3RXN1,XP_014056652.1,A0A1S3RXN1_SALSA,unreviewed,Purine nucleoside phosphorylase (EC 2.4.2.1) (...,LOC106605471,Salmo salar (Atlantic salmon),298
246776,TRINITY_DN99997_c3_g1_i3,4.0,0.0,3.0,2.0,0.0,2.0,8.0,2.814462,-0.536662,...,7.664873e-01,8.962630e-01,A0A1S3NK46,XP_014015630.1,A0A1S3NK46_SALSA,unreviewed,protein cordon-bleu-like isoform X1,LOC106579857,Salmo salar (Atlantic salmon),1565
246777,TRINITY_DN99997_c3_g1_i3,4.0,0.0,3.0,2.0,0.0,2.0,8.0,2.814462,-0.536662,...,7.664873e-01,8.962630e-01,A0A1S3NK46,XP_014015630.1,A0A1S3NK46_SALSA,unreviewed,protein cordon-bleu-like isoform X1,LOC106579857,Salmo salar (Atlantic salmon),1565
246778,TRINITY_DN99997_c4_g1_i1,57.0,58.0,38.0,42.0,29.0,47.0,12.0,39.286671,0.941784,...,5.718445e-02,2.089880e-01,A0A1S3RX94,XP_014056507.1,A0A1S3RX94_SALSA,unreviewed,protein cordon-bleu-like isoform X1,LOC106605414,Salmo salar (Atlantic salmon),1558
246779,TRINITY_DN99997_c4_g1_i1,57.0,58.0,38.0,42.0,29.0,47.0,12.0,39.286671,0.941784,...,5.718445e-02,2.089880e-01,A0A1S3RX94,XP_014056507.1,A0A1S3RX94_SALSA,unreviewed,protein cordon-bleu-like isoform X1,LOC106605414,Salmo salar (Atlantic salmon),1558
246780,TRINITY_DN99997_c4_g2_i2,41.0,63.0,44.0,69.0,63.0,52.0,21.0,48.950164,0.435372,...,3.560133e-01,6.170019e-01,A0A1S3RX94,XP_014056507.1,A0A1S3RX94_SALSA,unreviewed,protein cordon-bleu-like isoform X1,LOC106605414,Salmo salar (Atlantic salmon),1558
246781,TRINITY_DN99997_c4_g2_i2,41.0,63.0,44.0,69.0,63.0,52.0,21.0,48.950164,0.435372,...,3.560133e-01,6.170019e-01,A0A1S3RX94,XP_014056507.1,A0A1S3RX94_SALSA,unreviewed,protein cordon-bleu-like isoform X1,LOC106605414,Salmo salar (Atlantic salmon),1558
246782,TRINITY_DN99997_c4_g2_i5,251.0,197.0,232.0,271.0,260.0,373.0,201.0,246.757537,-0.043404,...,8.712646e-01,9.457296e-01,A0A1S3NJS1,XP_014015657.1,A0A1S3NJS1_SALSA,unreviewed,protein cordon-bleu-like isoform X4,LOC106579857,Salmo salar (Atlantic salmon),1550
246783,TRINITY_DN99997_c4_g6_i1,18.0,3.0,9.0,5.0,0.0,1.0,0.0,5.265968,4.764418,...,4.132578e-03,3.059041e-02,A0A1S3NQT5,XP_014017783.1,A0A1S3NQT5_SALSA,unreviewed,"serine--tRNA ligase, mitochondrial isoform X1",sars2,Salmo salar (Atlantic salmon),233
246784,TRINITY_DN99997_c4_g6_i1,18.0,3.0,9.0,5.0,0.0,1.0,0.0,5.265968,4.764418,...,4.132578e-03,3.059041e-02,A0A1S3NQT5,XP_014017783.1,A0A1S3NQT5_SALSA,unreviewed,"serine--tRNA ligase, mitochondrial isoform X1",sars2,Salmo salar (Atlantic salmon),233
246785,TRINITY_DN99998_c3_g1_i1,239.0,278.0,171.0,273.0,158.0,184.0,221.0,215.075349,0.460271,...,1.493598e-01,3.766258e-01,A0A1S3QB62,XP_014036654.1,A0A1S3QB62_SALSA,unreviewed,Acyl-CoA-binding domain-containing protein 5,acbd5,Salmo salar (Atlantic salmon),510
246786,TRINITY_DN99998_c3_g1_i1,239.0,278.0,171.0,273.0,158.0,184.0,221.0,215.075349,0.460271,...,1.493598e-01,3.766258e-01,A0A1S3QB62,XP_014036654.1,A0A1S3QB62_SALSA,unreviewed,Acyl-CoA-binding domain-containing protein 5,acbd5,Salmo salar (Atlantic salmon),510
246787,TRINITY_DN99998_c3_g3_i3,65.0,55.0,50.0,58.0,13.0,15.0,0.0,36.651030,2.847159,...,8.618881e-05,1.230958e-03,A0A1S3QB62,XP_014036654.1,A0A1S3QB62_SALSA,unreviewed,Acyl-CoA-binding domain-containing protein 5,acbd5,Salmo salar (Atlantic salmon),510
246788,TRINITY_DN99998_c3_g3_i3,65.0,55.0,50.0,58.0,13.0,15.0,0.0,36.651030,2.847159,...,8.618881e-05,1.230958e-03,A0A1S3QB62,XP_014036654.1,A0A1S3QB62_SALSA,unreviewed,Acyl-CoA-binding domain-containing protein 5,acbd5,Salmo salar (Atlantic salmon),510
246789,TRINITY_DN99998_c3_g3_i4,2.0,0.0,0.0,2.0,0.0,3.0,0.0,0.897903,0.308118,...,9.236848e-01,NaN,A0A1S3QB62,XP_014036654.1,A0A1S3QB62_SALSA,unreviewed,Acyl-CoA-binding domain-containing protein 5,acbd5,Salmo salar (Atlantic salmon),510
246790,TRINITY_DN99998_c3_g3_i4,2.0,0.0,0.0,2.0,0.0,3.0,0.0,0.897903,0.308118,...,9.236848e-01,NaN,A0A1S3QB62,XP_014036654.1,A0A1S3QB62_SALSA,unreviewed,Acyl-CoA-binding domain-containing protein 5,acbd5,Salmo salar (Atlantic salmon),510
246791,TRINITY_DN99999_c0_g1_i5,128.0,104.0,54.0,162.0,48.0,113.0,42.0,89.755103,0.911816,...,5.257330e-02,1.975568e-01,A0A1S3PME8,XP_014028776.1,A0A1S3PME8_SALSA,unreviewed,integral membrane protein GPR155-like isoform X1,LOC106586242,Salmo salar (Atlantic salmon),790
246792,TRINITY_DN99999_c0_g1_i6,284.0,299.0,227.0,319.0,146.0,270.0,76.0,225.432215,0.999741,...,6.584141e-03,4.406344e-02,A0A1S3PME8,XP_014028776.1,A0A1S3PME8_SALSA,unreviewed,integral membrane protein GPR155-like isoform X1,LOC106586242,Salmo salar (Atlantic salmon),790
246793,TRINITY_DN99999_c0_g1_i8,400.0,289.0,412.0,326.0,389.0,707.0,254.0,380.804723,-0.109011,...,7.571689e-01,8.917616e-01,A0A1S3NW63,XP_014019491.1,A0A1S3NW63_SALSA,unreviewed,integral membrane protein GPR155-like,LOC106581752,Salmo salar (Atlantic salmon),818
246794,TRINITY_DN99999_c0_g1_i8,400.0,289.0,412.0,326.0,389.0,707.0,254.0,380.804723,-0.109011,...,7.571689e-01,8.917616e-01,A0A1S3NW63,XP_014019491.1,A0A1S3NW63_SALSA,unreviewed,integral membrane protein GPR155-like,LOC106581752,Salmo salar (Atlantic salmon),818

In [54]:
prot_deseq_results_d6_merged_prot_details = pd.merge(prot_deseq_results_d6, prot_all_from_trinity_report, on='trinity', how='inner')
prot_deseq_results_d6_merged_prot_details.head()

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_6d_1,MC_6d_2,MC_6d_3,baseMean,log2FoldChange,...,pvalue,padj,Entry,ident,Entry name,Status,Protein names,Gene names,Organism,Length
0,TRINITY_DN100000_c5_g1_i2,0.0,3.0,2.0,0.0,0,0,0,0.801119,3.158985,...,3.803443e-01,NaN,A0A1S3PAG0,XP_014024532.1,A0A1S3PAG0_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106584141,Salmo salar (Atlantic salmon),754
1,TRINITY_DN100000_c5_g1_i6,374.0,506.0,607.0,594.0,192,195,227,400.698424,1.716315,...,1.049519e-08,6.674162e-08,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758
2,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1730,1743,1974,1365.742759,-0.324285,...,1.151943e-01,1.869944e-01,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333
3,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1730,1743,1974,1365.742759,-0.324285,...,1.151943e-01,1.869944e-01,B5X212,XP_014027367.1,CIO1B_SALSA,reviewed,Probable cytosolic iron-sulfur protein assembl...,ciao1b,Salmo salar (Atlantic salmon),333
4,TRINITY_DN100001_c2_g2_i7,562.0,408.0,311.0,353.0,1378,1338,1428,757.811676,-1.412238,...,3.941772e-07,2.029290e-06,A0A1S3NJU9,XP_014015694.1,A0A1S3NJU9_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106579887 CIAO1,Salmo salar (Atlantic salmon),330

In [55]:
prot_deseq_results_d9_merged_prot_details = pd.merge(prot_deseq_results_d9, prot_all_from_trinity_report, on='trinity', how='inner')
prot_deseq_results_d9_merged_prot_details.head()

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_9d_1,MC_9d_2,MC_9d_3,baseMean,log2FoldChange,...,pvalue,padj,Entry,ident,Entry name,Status,Protein names,Gene names,Organism,Length
0,TRINITY_DN100000_c5_g1_i2,0.0,3.0,2.0,0.0,5,0,0,1.393534,0.327664,...,0.902632,0.937984,A0A1S3PAG0,XP_014024532.1,A0A1S3PAG0_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106584141,Salmo salar (Atlantic salmon),754
1,TRINITY_DN100000_c5_g1_i6,374.0,506.0,607.0,594.0,427,219,339,460.552239,1.339117,...,0.000140,0.000620,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758
2,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,2315,2067,2386,1496.687824,-0.344909,...,0.071911,0.139669,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333
3,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,2315,2067,2386,1496.687824,-0.344909,...,0.071911,0.139669,B5X212,XP_014027367.1,CIO1B_SALSA,reviewed,Probable cytosolic iron-sulfur protein assembl...,ciao1b,Salmo salar (Atlantic salmon),333
4,TRINITY_DN100001_c2_g2_i7,562.0,408.0,311.0,353.0,1291,1139,1344,682.067860,-0.980119,...,0.000353,0.001414,A0A1S3NJU9,XP_014015694.1,A0A1S3NJU9_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106579887 CIAO1,Salmo salar (Atlantic salmon),330

In [29]:
prot_deseq_results_d1_merged_prot_details.shape

(246795, 22)

In [56]:
prot_deseq_results_d6_merged_prot_details.shape

(246795, 22)

In [57]:
prot_deseq_results_d9_merged_prot_details.shape

(246795, 22)

In [58]:
prot_deseq_results_d6_merged_prot_details = prot_deseq_results_d6_merged_prot_details[prot_deseq_results_d6_merged_prot_details['padj'] < 0.001]

In [61]:
prot_deseq_results_d9_merged_prot_details = prot_deseq_results_d9_merged_prot_details[prot_deseq_results_d9_merged_prot_details['padj'] < 0.001]

In [59]:
prot_deseq_results_d6_merged_prot_details.sort_values(by='log2FoldChange', inplace=True)

In [62]:
prot_deseq_results_d9_merged_prot_details.sort_values(by='log2FoldChange', inplace=True)

In [35]:
prot_deseq_results_d1_merged_prot_details.drop_duplicates(inplace=True)
prot_deseq_results_d1_merged_prot_details.shape

/home/maciek/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

(7419, 22)

In [60]:
prot_deseq_results_d6_merged_prot_details.drop_duplicates(inplace=True)
prot_deseq_results_d6_merged_prot_details.shape

(37964, 22)

In [63]:
prot_deseq_results_d9_merged_prot_details.drop_duplicates(inplace=True)
prot_deseq_results_d9_merged_prot_details.shape

(28874, 22)

## UTR / PROT

## D1

In [55]:
merged = pd.merge(mRNA_deseq_results_d1, prot_deseq_results_d1_merged_prot_details, on='Entry', how='inner', suffixes=('_UTR', '_PROT'))
merged.shape

(1874, 37)

In [56]:
#merged.to_csv(prot_path+'testowo.csv', index=False)

In [96]:
merged.drop_duplicates(inplace=True)
merged.shape

(1874, 37)

In [ ]:
# zestawienie L2FC w droch grupach, obejmuje tylko grupy ktore sie zmienily, tzn nie ma tu takich
# ktore zmianom nie ulegly, np. UTR_UP i PROT_NONE (up po MC w UTR, ale w bialkach bez zmiany)
# zeby to zrobic musze porownac

In [87]:
UTR_UP_PROT_UP = merged[(merged['log2FoldChange_UTR'] < 0) & (merged['log2FoldChange_PROT'] < 0)]

In [88]:
UTR_UP_PROT_DOWN = merged[(merged['log2FoldChange_UTR'] < 0) & (merged['log2FoldChange_PROT'] > 0)]

In [89]:
UTR_DOWN_PROT_UP = merged[(merged['log2FoldChange_UTR'] > 0) & (merged['log2FoldChange_PROT'] < 0)]

In [90]:
UTR_DOWN_PROT_DOWN = merged[(merged['log2FoldChange_UTR'] > 0) & (merged['log2FoldChange_PROT'] > 0)]

In [ ]:
# ponizsze, zgodnie ze znakami: w deseq mam znaki odwrotnie, tzn, jesli po MC jest wzrost to mam znak "-"
# i dlatego UP ma znak '<'

In [91]:
UTR_UP_PROT_UP.shape

(1549, 37)

In [92]:
UTR_UP_PROT_DOWN.shape

(55, 37)

In [93]:
UTR_DOWN_PROT_UP.shape

(63, 37)

In [94]:
UTR_DOWN_PROT_DOWN.shape

(207, 37)

In [98]:
# wrzucamy to do uniprota w celu jakiejs funkcjonalnosc oznaczenia.
UTR_UP_PROT_UP['Entry'].to_csv(prot_path+'entry_prot.csv', index=False)

## D6

In [64]:
merged = pd.merge(mRNA_deseq_results_d6, prot_deseq_results_d6_merged_prot_details, on='Entry', how='inner', suffixes=('_UTR', '_PROT'))
merged.shape

(19981, 37)

In [56]:
#merged.to_csv(prot_path+'testowo.csv', index=False)

In [65]:
merged.drop_duplicates(inplace=True)
merged.shape

(19981, 37)

In [ ]:
# zestawienie L2FC w droch grupach, obejmuje tylko grupy ktore sie zmienily, tzn nie ma tu takich
# ktore zmianom nie ulegly, np. UTR_UP i PROT_NONE (up po MC w UTR, ale w bialkach bez zmiany)
# zeby to zrobic musze porownac

In [66]:
UTR_UP_PROT_UP = merged[(merged['log2FoldChange_UTR'] < 0) & (merged['log2FoldChange_PROT'] < 0)]

In [67]:
UTR_UP_PROT_DOWN = merged[(merged['log2FoldChange_UTR'] < 0) & (merged['log2FoldChange_PROT'] > 0)]

In [68]:
UTR_DOWN_PROT_UP = merged[(merged['log2FoldChange_UTR'] > 0) & (merged['log2FoldChange_PROT'] < 0)]

In [69]:
UTR_DOWN_PROT_DOWN = merged[(merged['log2FoldChange_UTR'] > 0) & (merged['log2FoldChange_PROT'] > 0)]

In [ ]:
# ponizsze, zgodnie ze znakami: w deseq mam znaki odwrotnie, tzn, jesli po MC jest wzrost to mam znak "-"
# i dlatego UP ma znak '<'

In [70]:
UTR_UP_PROT_UP.shape

(7512, 37)

In [71]:
UTR_UP_PROT_DOWN.shape

(1812, 37)

In [72]:
UTR_DOWN_PROT_UP.shape

(1738, 37)

In [73]:
UTR_DOWN_PROT_DOWN.shape

(8919, 37)

In [98]:
# wrzucamy to do uniprota w celu jakiejs funkcjonalnosc oznaczenia.
UTR_UP_PROT_UP['Entry'].to_csv(prot_path+'entry_prot.csv', index=False)

## D9

In [74]:
merged = pd.merge(mRNA_deseq_results_d9, prot_deseq_results_d9_merged_prot_details, on='Entry', how='inner', suffixes=('_UTR', '_PROT'))
merged.shape

(11511, 37)

In [56]:
#merged.to_csv(prot_path+'testowo.csv', index=False)

In [75]:
merged.drop_duplicates(inplace=True)
merged.shape

(11511, 37)

In [ ]:
# zestawienie L2FC w droch grupach, obejmuje tylko grupy ktore sie zmienily, tzn nie ma tu takich
# ktore zmianom nie ulegly, np. UTR_UP i PROT_NONE (up po MC w UTR, ale w bialkach bez zmiany)
# zeby to zrobic musze porownac

In [76]:
UTR_UP_PROT_UP = merged[(merged['log2FoldChange_UTR'] < 0) & (merged['log2FoldChange_PROT'] < 0)]

In [77]:
UTR_UP_PROT_DOWN = merged[(merged['log2FoldChange_UTR'] < 0) & (merged['log2FoldChange_PROT'] > 0)]

In [78]:
UTR_DOWN_PROT_UP = merged[(merged['log2FoldChange_UTR'] > 0) & (merged['log2FoldChange_PROT'] < 0)]

In [79]:
UTR_DOWN_PROT_DOWN = merged[(merged['log2FoldChange_UTR'] > 0) & (merged['log2FoldChange_PROT'] > 0)]

In [ ]:
# ponizsze, zgodnie ze znakami: w deseq mam znaki odwrotnie, tzn, jesli po MC jest wzrost to mam znak "-"
# i dlatego UP ma znak '<'

In [80]:
UTR_UP_PROT_UP.shape

(5211, 37)

In [81]:
UTR_UP_PROT_DOWN.shape

(818, 37)

In [82]:
UTR_DOWN_PROT_UP.shape

(924, 37)

In [83]:
UTR_DOWN_PROT_DOWN.shape

(4558, 37)

In [98]:
# wrzucamy to do uniprota w celu jakiejs funkcjonalnosc oznaczenia.
UTR_UP_PROT_UP['Entry'].to_csv(prot_path+'entry_prot.csv', index=False)