In [1]:
import pandas as pd
import numpy as np

In [2]:
path='/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/'

# BEGIN // dotyczy:
I am interested in exploring whether there is a difference in the ratio A/B between the two conditions. Just to clarify: I am not interested in finding out whether there are significant differences between A and B (there are), but whether those differences between A and B change between condition treated vs. untreated.

In [150]:
UTR = pd.read_csv(path+'mRNA_only_merged_w_XP.csv')
UTR.head(1)

,query,al_title,al_accession,evalue,coverage,Entry,Protein names,Gene names
0,TRINITY_DN100004_c4_g2_i2,gi|929290304|ref|XM_014166828.1| PREDICTED: Sa...,XM_014166828,0.0,100.183824,A0A1S3P3U9,forkhead box protein P4-like isoform X8,LOC106583051

In [151]:
UTR = UTR[['query', 'Entry']]
UTR.head(1)

                       query       Entry
0  TRINITY_DN100004_c4_g2_i2  A0A1S3P3U9

In [152]:
UTR.rename(columns={'query':'trinity'}, inplace=True)

In [153]:
UTR.head(1)

                     trinity       Entry
0  TRINITY_DN100004_c4_g2_i2  A0A1S3P3U9

In [154]:
matryca_novel = pd.read_csv(path+'PBS1d_MC_all_matryca.csv')
matryca_novel.head()

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,MC_6d_1,MC_6d_2,MC_6d_3,MC_9d_1,MC_9d_2,MC_9d_3
0,TRINITY_DN100003_c1_g1_i1,8,16,29,1,24,21,24,1,1,2,7,2,34
1,TRINITY_DN100004_c4_g2_i2,9,22,24,8,23,50,45,65,53,95,76,29,74
2,TRINITY_DN100005_c7_g2_i1,800,798,577,913,1322,1276,1285,6952,5736,4279,6616,4073,3119
3,TRINITY_DN100005_c8_g3_i1,101,102,92,248,52,56,71,89,189,138,313,327,278
4,TRINITY_DN100005_c9_g1_i1,19,4,22,4,2,2,1,0,1,0,2,6,18

In [21]:
matryca_novel.shape

(188998, 14)

In [164]:
matryca_w_entry = pd.merge(UTR, matryca_novel, on='trinity', how='inner')
matryca_w_entry.head()

,trinity,Entry,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,MC_6d_1,MC_6d_2,MC_6d_3,MC_9d_1,MC_9d_2,MC_9d_3
0,TRINITY_DN100004_c4_g2_i2,A0A1S3P3U9,9,22,24,8,23,50,45,65,53,95,76,29,74
1,TRINITY_DN100005_c7_g2_i1,A0A1S3SUX9,800,798,577,913,1322,1276,1285,6952,5736,4279,6616,4073,3119
2,TRINITY_DN81030_c8_g4_i1,A0A1S3SUX9,47,44,18,47,62,74,62,335,306,196,292,162,121
3,TRINITY_DN83202_c8_g4_i2,A0A1S3SUX9,35,21,30,30,13,28,32,8,6,13,21,15,38
4,TRINITY_DN105298_c5_g1_i2,A0A1S3SUX9,23,15,19,25,7,12,10,1,13,8,22,8,13

In [156]:
matryca_w_entry.shape #mamy tu tylko trinity zidentyfikowane jako mRNA bialka (UTR)

(93208, 15)

In [165]:
matryca_w_entry.columns = [str(col) + '_UTR' for col in matryca_w_entry.columns]

In [166]:
matryca_w_entry.rename(columns={'Entry_UTR':'Entry', 'trinity_UTR':'id_UTR'}, inplace=True)

In [167]:
matryca_w_entry.head()

,id_UTR,Entry,PBS_1d_1_UTR,PBS_1d_2_UTR,PBS_1d_3_UTR,PBS_1d_4_UTR,MC_1d_1_UTR,MC_1d_2_UTR,MC_1d_3_UTR,MC_6d_1_UTR,MC_6d_2_UTR,MC_6d_3_UTR,MC_9d_1_UTR,MC_9d_2_UTR,MC_9d_3_UTR
0,TRINITY_DN100004_c4_g2_i2,A0A1S3P3U9,9,22,24,8,23,50,45,65,53,95,76,29,74
1,TRINITY_DN100005_c7_g2_i1,A0A1S3SUX9,800,798,577,913,1322,1276,1285,6952,5736,4279,6616,4073,3119
2,TRINITY_DN81030_c8_g4_i1,A0A1S3SUX9,47,44,18,47,62,74,62,335,306,196,292,162,121
3,TRINITY_DN83202_c8_g4_i2,A0A1S3SUX9,35,21,30,30,13,28,32,8,6,13,21,15,38
4,TRINITY_DN105298_c5_g1_i2,A0A1S3SUX9,23,15,19,25,7,12,10,1,13,8,22,8,13

## BIAŁKA PROT

In [18]:
matryca_w_entry.head()

,Entry,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,MC_6d_1,MC_6d_2,MC_6d_3,MC_9d_1,MC_9d_2,MC_9d_3
0,A0A1S3P3U9,9,22,24,8,23,50,45,65,53,95,76,29,74
1,A0A1S3SUX9,800,798,577,913,1322,1276,1285,6952,5736,4279,6616,4073,3119
2,A0A1S3SUX9,47,44,18,47,62,74,62,335,306,196,292,162,121
3,A0A1S3SUX9,35,21,30,30,13,28,32,8,6,13,21,15,38
4,A0A1S3SUX9,23,15,19,25,7,12,10,1,13,8,22,8,13

In [46]:
# BIALKA:

salmo_rep_with_annot = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/1_code/report_salmo_annot_feature_map_salmo_proteins_xp01.csv', sep='\t', low_memory=False)

In [48]:
salmo_rep_with_annot.head()

                          id           ident
0     TRINITY_DN100000_c5_g1  XP_013978521.1
1  TRINITY_DN100000_c5_g1_i2  XP_014024532.1
2  TRINITY_DN100000_c5_g1_i6  XP_013978521.1
3     TRINITY_DN100000_c9_g1             NaN
4  TRINITY_DN100000_c9_g1_i1             NaN

In [49]:
salmo_rep_with_annot.shape

(332030, 2)

In [50]:
salmo_rep_with_annot.dropna(inplace=True)
salmo_rep_with_annot.shape

(257125, 2)

In [57]:
salmo_rep_with_annot.head()

                          id           ident
0     TRINITY_DN100000_c5_g1  XP_013978521.1
1  TRINITY_DN100000_c5_g1_i2  XP_014024532.1
2  TRINITY_DN100000_c5_g1_i6  XP_013978521.1
7     TRINITY_DN100001_c2_g2  XP_014027367.1
8  TRINITY_DN100001_c2_g2_i2  XP_014027367.1

In [41]:
salmo_rep_with_annot.dtypes

id       object
ident    object
dtype: object

In [52]:
salmo_rep_with_annot['ident'].to_csv(path+'xp_to_uniref.txt', index=False)

In [58]:
# zawiera wszystkie bialka zidentyfikowane przez trinotate i przypisane im Entry z uniprota

uniref_from_trinotate = pd.read_csv(path+'uniprot-yourlist-xp_to_uniref.tab', sep='\t')
uniref_from_trinotate.head()

,Entry,ident,Entry name,Status,Protein names,Gene names,Organism,Length
0,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758
1,A0A1S3PAG0,XP_014024532.1,A0A1S3PAG0_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106584141,Salmo salar (Atlantic salmon),754
2,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333
3,B5X212,XP_014027367.1,CIO1B_SALSA,reviewed,Probable cytosolic iron-sulfur protein assembl...,ciao1b,Salmo salar (Atlantic salmon),333
4,A0A1S3NJU9,XP_014015694.1,A0A1S3NJU9_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106579887 CIAO1,Salmo salar (Atlantic salmon),330

In [112]:
#salmo_rep_with_annot_split = pd.DataFrame(salmo_rep_with_annot['ident'].str.split('^').tolist(), index=salmo_rep_with_annot.id).stack()
#salmo_rep_with_annot_split = salmo_rep_with_annot_split.reset_index([0, 'id'])
#salmo_rep_with_annot_split

In [113]:
#uniref_from_trinotate_entry_indent = uniref_from_trinotate[['Entry', 'ident']]
#uniref_from_trinotate_entry_indent.head()

In [114]:
salmo_rep_with_annot_w_entry = pd.merge(uniref_from_trinotate, salmo_rep_with_annot, on='ident', how='inner')
salmo_rep_with_annot_w_entry.head()

,Entry,ident,Entry name,Status,Protein names,Gene names,Organism,Length,id
0,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758,TRINITY_DN100000_c5_g1
1,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758,TRINITY_DN100000_c5_g1_i6
2,A0A1S3PAG0,XP_014024532.1,A0A1S3PAG0_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106584141,Salmo salar (Atlantic salmon),754,TRINITY_DN100000_c5_g1_i2
3,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333,TRINITY_DN100001_c2_g2
4,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333,TRINITY_DN100001_c2_g2_i2

In [115]:
salmo_rep_with_annot_w_entry.shape

(429071, 9)

In [66]:
#salmo_rep_with_annot_w_entry.to_csv(path+'test.csv')

In [116]:
prot_path = '/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/proteins_salmo/'
proteins_matryca = pd.read_csv(prot_path+'PBS_MCLR_salmo_only_matryca.csv')
proteins_matryca.head()

,id,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,MC_6d_1,MC_6d_2,MC_6d_3,MC_9d_1,MC_9d_2,MC_9d_3
0,TRINITY_DN100000_c5_g1_i2,0.0,3.0,2.0,0.0,0.0,0.0,0.0,0,0,0,5,0,0
1,TRINITY_DN100000_c5_g1_i6,374.0,506.0,607.0,594.0,511.0,726.0,517.0,192,195,227,427,219,339
2,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1162.0,1784.0,938.0,1730,1743,1974,2315,2067,2386
3,TRINITY_DN100001_c2_g2_i7,562.0,408.0,311.0,353.0,402.0,471.0,420.0,1378,1338,1428,1291,1139,1344
4,TRINITY_DN100001_c2_g3_i3,565.0,525.0,384.0,406.0,555.0,552.0,529.0,1553,1461,1684,1436,1416,1447

In [117]:
proteins_matryca.shape

(148647, 14)

In [118]:
proteins_matryca_w_entry = pd.merge(proteins_matryca, salmo_rep_with_annot_w_entry, on='id', how='inner')
proteins_matryca_w_entry.drop_duplicates(inplace=True)
proteins_matryca_w_entry.shape

(149296, 22)

In [96]:
#proteins_matryca_w_entry.to_csv(path+'test.csv')

In [119]:
test_if_merged_correctly = proteins_matryca_w_entry[~proteins_matryca_w_entry['id'].isin(proteins_matryca['id'])]
test_if_merged_correctly.shape

(0, 22)

In [98]:
#del proteins_matryca_w_entry['id']
#del proteins_matryca_w_entry['ident']

In [120]:
proteins_matryca_w_entry.columns = [str(col) + '_PROT' for col in proteins_matryca_w_entry.columns]

In [122]:
proteins_matryca_w_entry.rename(columns={'Entry_PROT':'Entry'}, inplace=True)

In [123]:
proteins_matryca_w_entry.head()

,id_PROT,PBS_1d_1_PROT,PBS_1d_2_PROT,PBS_1d_3_PROT,PBS_1d_4_PROT,MC_1d_1_PROT,MC_1d_2_PROT,MC_1d_3_PROT,MC_6d_1_PROT,MC_6d_2_PROT,...,MC_9d_2_PROT,MC_9d_3_PROT,Entry,ident_PROT,Entry name_PROT,Status_PROT,Protein names_PROT,Gene names_PROT,Organism_PROT,Length_PROT
0,TRINITY_DN100000_c5_g1_i2,0.0,3.0,2.0,0.0,0.0,0.0,0.0,0,0,...,0,0,A0A1S3PAG0,XP_014024532.1,A0A1S3PAG0_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106584141,Salmo salar (Atlantic salmon),754
1,TRINITY_DN100000_c5_g1_i6,374.0,506.0,607.0,594.0,511.0,726.0,517.0,192,195,...,219,339,A0A1S3KIG4,XP_013978521.1,A0A1S3KIG4_SALSA,unreviewed,carboxyl-terminal PDZ ligand of neuronal nitri...,LOC106560293,Salmo salar (Atlantic salmon),758
2,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1162.0,1784.0,938.0,1730,1743,...,2067,2386,A0A1S3PIA6,XP_014027367.1,A0A1S3PIA6_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106585549 CIAO1,Salmo salar (Atlantic salmon),333
3,TRINITY_DN100001_c2_g2_i2,1232.0,1264.0,998.0,1040.0,1162.0,1784.0,938.0,1730,1743,...,2067,2386,B5X212,XP_014027367.1,CIO1B_SALSA,reviewed,Probable cytosolic iron-sulfur protein assembl...,ciao1b,Salmo salar (Atlantic salmon),333
4,TRINITY_DN100001_c2_g2_i7,562.0,408.0,311.0,353.0,402.0,471.0,420.0,1378,1338,...,1139,1344,A0A1S3NJU9,XP_014015694.1,A0A1S3NJU9_SALSA,unreviewed,Probable cytosolic iron-sulfur protein assembl...,LOC106579887 CIAO1,Salmo salar (Atlantic salmon),330

In [124]:
matryca_w_entry.shape #UTR

(93208, 14)

In [125]:
proteins_matryca_w_entry.shape #PROT

(149296, 22)

In [168]:
# do UTR dodac PROT

merged_UTR_PROT_matryca = pd.merge(matryca_w_entry, proteins_matryca_w_entry, on="Entry", how='inner')
#merged.to_csv(path+'matryca_UTR_PROT_entry_only.csv', index=False)

In [169]:
merged_UTR_PROT_matryca.columns

Index(['id_UTR', 'Entry', 'PBS_1d_1_UTR', 'PBS_1d_2_UTR', 'PBS_1d_3_UTR',
       'PBS_1d_4_UTR', 'MC_1d_1_UTR', 'MC_1d_2_UTR', 'MC_1d_3_UTR',
       'MC_6d_1_UTR', 'MC_6d_2_UTR', 'MC_6d_3_UTR', 'MC_9d_1_UTR',
       'MC_9d_2_UTR', 'MC_9d_3_UTR', 'id_PROT', 'PBS_1d_1_PROT',
       'PBS_1d_2_PROT', 'PBS_1d_3_PROT', 'PBS_1d_4_PROT', 'MC_1d_1_PROT',
       'MC_1d_2_PROT', 'MC_1d_3_PROT', 'MC_6d_1_PROT', 'MC_6d_2_PROT',
       'MC_6d_3_PROT', 'MC_9d_1_PROT', 'MC_9d_2_PROT', 'MC_9d_3_PROT',
       'ident_PROT', 'Entry name_PROT', 'Status_PROT', 'Protein names_PROT',
       'Gene names_PROT', 'Organism_PROT', 'Length_PROT'],
      dtype='object')

In [130]:
day_1_matryca = merged_UTR_PROT_matryca[['PBS_1d_1_UTR', 'PBS_1d_2_UTR', 'PBS_1d_3_UTR', 'PBS_1d_4_UTR',
       'MC_1d_1_UTR', 'MC_1d_2_UTR', 'MC_1d_3_UTR', 'PBS_1d_1_PROT', 'PBS_1d_2_PROT',
       'PBS_1d_3_PROT', 'PBS_1d_4_PROT', 'MC_1d_1_PROT', 'MC_1d_2_PROT',
       'MC_1d_3_PROT']]

day_1_matryca.to_csv(path+'day_1_UTR_PROT_matryca.csv', index=False)

# na podstawie powyzszego ^^ robiebie deseq2

In [178]:
# ponizej wczytuje wyniki deseq i dodaje do nich kolumny z merged_UTR_PROT_matryca

deseq_day_1_results = pd.read_csv(path+'deseq2_result_from_R_1d.csv')

In [179]:
merged_UTR_PROT_matryca.shape

(295223, 36)

In [183]:
deseq_day_1_results.shape

(295223, 6)

In [184]:
deseq_day_1_results_w_all_details = pd.merge(deseq_day_1_results, merged_UTR_PROT_matryca, left_index=True, right_index=True)
deseq_day_1_results_w_all_details.shape

(295223, 42)

In [185]:
deseq_day_1_results_w_all_details = deseq_day_1_results_w_all_details[['baseMean', 'log2FoldChange', 'lfcSE', 'stat', 'pvalue', 'padj',
       'Entry', 'PBS_1d_1_UTR', 'PBS_1d_2_UTR', 'PBS_1d_3_UTR', 'PBS_1d_4_UTR',
       'MC_1d_1_UTR', 'MC_1d_2_UTR', 'MC_1d_3_UTR', 'id_UTR', 'id_PROT', 'PBS_1d_1_PROT', 'PBS_1d_2_PROT',
       'PBS_1d_3_PROT', 'PBS_1d_4_PROT', 'MC_1d_1_PROT', 'MC_1d_2_PROT',
       'MC_1d_3_PROT', 'ident_PROT', 'Entry name_PROT', 'Status_PROT', 'Protein names_PROT',
       'Gene names_PROT', 'Organism_PROT', 'Length_PROT']]

In [186]:
deseq_day_1_results_w_all_details = deseq_day_1_results_w_all_details[deseq_day_1_results_w_all_details['padj'] < 0.001]

In [187]:
deseq_day_1_results_w_all_details.sort_values(by='log2FoldChange', inplace=True)

In [188]:
deseq_day_1_results_w_all_details.to_csv(path+'deseq_result_1d_with_all_details.csv', index=False)

# END ///// dotyczy:
I am interested in exploring whether there is a difference in the ratio A/B between the two conditions. Just to clarify: I am not interested in finding out whether there are significant differences between A and B (there are), but whether those differences between A and B change between condition treated vs. untreated.

# BEGIN /// 
### deseq UTR i PROT oddzielnie i porownanie ze soba juz tylko wynikow log2fc

najpierw: deseq wszystkich sekwencji (matryca novel), a potem wybranie z nich mRNA

In [36]:
matryca_novel = pd.read_csv(path+'PBS1d_MC_all_matryca.csv')
matryca_novel.head()

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,MC_6d_1,MC_6d_2,MC_6d_3,MC_9d_1,MC_9d_2,MC_9d_3
0,TRINITY_DN100003_c1_g1_i1,8,16,29,1,24,21,24,1,1,2,7,2,34
1,TRINITY_DN100004_c4_g2_i2,9,22,24,8,23,50,45,65,53,95,76,29,74
2,TRINITY_DN100005_c7_g2_i1,800,798,577,913,1322,1276,1285,6952,5736,4279,6616,4073,3119
3,TRINITY_DN100005_c8_g3_i1,101,102,92,248,52,56,71,89,189,138,313,327,278
4,TRINITY_DN100005_c9_g1_i1,19,4,22,4,2,2,1,0,1,0,2,6,18

In [37]:
matryca_novel.shape

(188998, 14)

In [44]:
matryca_novel.columns

Index(['trinity', 'PBS_1d_1', 'PBS_1d_2', 'PBS_1d_3', 'PBS_1d_4', 'MC_1d_1',
       'MC_1d_2', 'MC_1d_3', 'MC_6d_1', 'MC_6d_2', 'MC_6d_3', 'MC_9d_1',
       'MC_9d_2', 'MC_9d_3'],
      dtype='object')

In [45]:
matryca_novel_1d = matryca_novel[['trinity', 'PBS_1d_1', 'PBS_1d_2', 'PBS_1d_3', 'PBS_1d_4', 'MC_1d_1',
       'MC_1d_2', 'MC_1d_3']]

In [48]:
# po deseq2:

#zaladuj wyniki deseq
novel_deseq_results_d1 = pd.read_csv(path+'NOVEL_deseq2_result_from_R_1d.csv')

In [49]:
# dodaj kolumny trinity oraz RC poszczegolnych grup do wynikow deseq:
novel_deseq_results_d1 = pd.concat([matryca_novel_1d, novel_deseq_results_d1], axis=1, sort=False)

In [50]:
novel_deseq_results_d1.head()

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,TRINITY_DN100003_c1_g1_i1,8,16,29,1,24,21,24,17.558741,-0.889708,0.915032,-0.972325,0.330889,0.597653
1,TRINITY_DN100004_c4_g2_i2,9,22,24,8,23,50,45,25.610719,-1.435470,0.664879,-2.158995,0.030851,0.139013
2,TRINITY_DN100005_c7_g2_i1,800,798,577,913,1322,1276,1285,981.922026,-0.885334,0.305707,-2.896020,0.003779,0.031316
3,TRINITY_DN100005_c8_g3_i1,101,102,92,248,52,56,71,98.505396,1.020068,0.501867,2.032548,0.042098,0.168550
4,TRINITY_DN100005_c9_g1_i1,19,4,22,4,2,2,1,7.462803,2.825120,1.207046,2.340524,0.019257,0.101486

In [51]:
novel_deseq_results_d1 = novel_deseq_results_d1[novel_deseq_results_d1['padj'] < 0.001]

In [52]:
novel_deseq_results_d1.sort_values(by='log2FoldChange', inplace=True)

In [53]:
novel_deseq_results_d1.to_csv(path+'NOVEL_deseq2_result_from_R_1d_padj-filtered_l2fc-sorted.csv', index=False)

In [ ]:
# filtrowanie tylko mRNA UTR ze wszystkich trinity, ktore to zawiera powyzsza matryca

In [61]:
UTR = pd.read_csv(path+'mRNA_only_merged_w_XP.csv')
UTR.head(1)

,query,al_title,al_accession,evalue,coverage,Entry,Protein names,Gene names
0,TRINITY_DN100004_c4_g2_i2,gi|929290304|ref|XM_014166828.1| PREDICTED: Sa...,XM_014166828,0.0,100.183824,A0A1S3P3U9,forkhead box protein P4-like isoform X8,LOC106583051

In [62]:
UTR = UTR[['query', 'Entry', 'Protein names']]
UTR.head(1)

,query,Entry,Protein names
0,TRINITY_DN100004_c4_g2_i2,A0A1S3P3U9,forkhead box protein P4-like isoform X8

In [63]:
UTR.rename(columns={'query':'trinity'}, inplace=True)

In [64]:
UTR.head(1)

,trinity,Entry,Protein names
0,TRINITY_DN100004_c4_g2_i2,A0A1S3P3U9,forkhead box protein P4-like isoform X8

In [66]:
mRNA_deseq_results_d1 = pd.merge(UTR, novel_deseq_results_d1, on='trinity', how='inner')
mRNA_deseq_results_d1.head()

,trinity,Entry,Protein names,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_1d_1,MC_1d_2,MC_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,TRINITY_DN91961_c5_g1_i1,A0A1S3SUX9,"alpha-N-acetylgalactosaminide alpha-2,6-sialyl...",42,64,60,68,10,6,1,33.540847,3.280342,0.665130,4.931881,8.144168e-07,0.000029
1,TRINITY_DN100005_c8_g1_i1,A0A1S3RIW2,voltage-gated potassium channel subunit beta-2...,55,10,44,4,0,0,0,15.621958,7.190425,1.603170,4.485130,7.286939e-06,0.000189
2,TRINITY_DN87843_c1_g5_i1,A0A1S3RIW2,voltage-gated potassium channel subunit beta-2...,0,0,0,0,19,18,14,7.386073,-6.643863,1.481979,-4.483101,7.356598e-06,0.000190
3,TRINITY_DN100612_c4_g1_i1,A0A1S3PZ28,chloride intracellular channel protein 1-like,0,0,1,2,83,54,10,20.890636,-6.097034,1.207566,-5.049029,4.440618e-07,0.000017
4,TRINITY_DN96978_c1_g1_i1,A0A1S3RQE3,ETS-related transcription factor Elf-1-like is...,11,12,8,9,33,87,113,40.140099,-3.115138,0.626264,-4.974161,6.553077e-07,0.000024

In [67]:
#mamy tu wynik deseq 1d dla UTR (zidentyfikowane jako mRNA w blast'cie)
#deseq robiony w R
#teraz wystarczy zrobic jeszcze deseq dla 1d bialek prawdziwych (;)) i porownac je po entry z tymi tu UTR'ami
mRNA_deseq_results_d1.shape

(3010, 16)